"""initial schema

Revision ID: 19140a648fb3
Revises: 
Create Date: 2026-09-15 16:11:29.099803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19140a648fb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oracle_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('oracle_text', sa.Text(), nullable=True),
    sa.Column('mana_cost', sa.String(), nullable=True),
    sa.Column('mana_value', sa.Float(), nullable=True),
    sa.Column('colors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('color_identity', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('types', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('released_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.create_index(op.f('ix_cards_oracle_id'), 'cards', ['oracle_id'], unique=True)
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('archetype', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('winrate', sa.Float(), nullable=True),
    sa.Column('meta_share', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_archetype'), 'decks', ['archetype'], unique=False)
    op.create_index(op.f('ix_decks_format'), 'decks', ['format'], unique=False)
    op.create_index(op.f('ix_decks_id'), 'decks', ['id'], unique=False)
    op.create_index(op.f('ix_decks_name'), 'decks', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('card_legalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('standard', sa.Boolean(), nullable=True),
    sa.Column('alchemy', sa.Boolean(), nullable=True),
    sa.Column('explorer', sa.Boolean(), nullable=True),
    sa.Column('historic', sa.Boolean(), nullable=True),
    sa.Column('timeless', sa.Boolean(), nullable=True),
    sa.Column('brawl', sa.Boolean(), nullable=True),
    sa.Column('rotates_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id')
    )
    op.create_index(op.f('ix_card_legalities_id'), 'card_legalities', ['id'], unique=False)
    op.create_table('card_prints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('scryfall_id', sa.String(), nullable=True),
    sa.Column('set_code', sa.String(), nullable=True),
    sa.Column('collector_number', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_prints_id'), 'card_prints', ['id'], unique=False)
    op.create_index(op.f('ix_card_prints_rarity'), 'card_prints', ['rarity'], unique=False)
    op.create_index(op.f('ix_card_prints_scryfall_id'), 'card_prints', ['scryfall_id'], unique=True)
    op.create_index(op.f('ix_card_prints_set_code'), 'card_prints', ['set_code'], unique=False)
    op.create_table('card_synergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_a_id', sa.Integer(), nullable=False),
    sa.Column('card_b_id', sa.Integer(), nullable=False),
    sa.Column('synergy_type', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_a_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['card_b_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_a_id', 'card_b_id', name='uq_card_synergy')
    )
    op.create_index(op.f('ix_card_synergies_card_a_id'), 'card_synergies', ['card_a_id'], unique=False)
    op.create_index(op.f('ix_card_synergies_card_b_id'), 'card_synergies', ['card_b_id'], unique=False)
    op.create_index(op.f('ix_card_synergies_format'), 'card_synergies', ['format'], unique=False)
    op.create_index(op.f('ix_card_synergies_id'), 'card_synergies', ['id'], unique=False)
    op.create_table('card_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'tag', name='uq_card_tag')
    )
    op.create_index(op.f('ix_card_tags_id'), 'card_tags', ['id'], unique=False)
    op.create_index(op.f('ix_card_tags_tag'), 'card_tags', ['tag'], unique=False)
    op.create_table('deck_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('synergy_score', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('mana_score', sa.Float(), nullable=True),
    sa.Column('meta_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_analyses_id'), 'deck_analyses', ['id'], unique=False)
    op.create_table('deck_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_cards_id'), 'deck_cards', ['id'], unique=False)
    op.create_table('match_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('opponent_id', sa.String(), nullable=True),
    sa.Column('deck_name', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_histories_deck_name'), 'match_histories', ['deck_name'], unique=False)
    op.create_index(op.f('ix_match_histories_format'), 'match_histories', ['format'], unique=False)
    op.create_index(op.f('ix_match_histories_id'), 'match_histories', ['id'], unique=False)
    op.create_table('meta_card_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('appearance_rate', sa.Float(), nullable=True),
    sa.Column('winrate', sa.Float(), nullable=True),
    sa.Column('decks_played', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'format', name='uq_meta_card_format')
    )
    op.create_index(op.f('ix_meta_card_stats_format'), 'meta_card_stats', ['format'], unique=False)
    op.create_index(op.f('ix_meta_card_stats_id'), 'meta_card_stats', ['id'], unique=False)
    op.create_table('user_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_user_card')
    )
    op.create_index(op.f('ix_user_collections_id'), 'user_collections', ['id'], unique=False)
    op.create_table('wildcard_inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('common', sa.Integer(), nullable=True),
    sa.Column('uncommon', sa.Integer(), nullable=True),
    sa.Column('rare', sa.Integer(), nullable=True),
    sa.Column('mythic', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wildcard_inventories_id'), 'wildcard_inventories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wildcard_inventories_id'), table_name='wildcard_inventories')
    op.drop_table('wildcard_inventories')
    op.drop_index(op.f('ix_user_collections_id'), table_name='user_collections')
    op.drop_table('user_collections')
    op.drop_index(op.f('ix_meta_card_stats_id'), table_name='meta_card_stats')
    op.drop_index(op.f('ix_meta_card_stats_format'), table_name='meta_card_stats')
    op.drop_table('meta_card_stats')
    op.drop_index(op.f('ix_match_histories_id'), table_name='match_histories')
    op.drop_index(op.f('ix_match_histories_format'), table_name='match_histories')
    op.drop_index(op.f('ix_match_histories_deck_name'), table_name='match_histories')
    op.drop_table('match_histories')
    op.drop_index(op.f('ix_deck_cards_id'), table_name='deck_cards')
    op.drop_table('deck_cards')
    op.drop_index(op.f('ix_deck_analyses_id'), table_name='deck_analyses')
    op.drop_table('deck_analyses')
    op.drop_index(op.f('ix_card_tags_tag'), table_name='card_tags')
    op.drop_index(op.f('ix_card_tags_id'), table_name='card_tags')
    op.drop_table('card_tags')
    op.drop_index(op.f('ix_card_synergies_id'), table_name='card_synergies')
    op.drop_index(op.f('ix_card_synergies_format'), table_name='card_synergies')
    op.drop_index(op.f('ix_card_synergies_card_b_id'), table_name='card_synergies')
    op.drop_index(op.f('ix_card_synergies_card_a_id'), table_name='card_synergies')
    op.drop_table('card_synergies')
    op.drop_index(op.f('ix_card_prints_set_code'), table_name='card_prints')
    op.drop_index(op.f('ix_card_prints_scryfall_id'), table_name='card_prints')
    op.drop_index(op.f('ix_card_prints_rarity'), table_name='card_prints')
    op.drop_index(op.f('ix_card_prints_id'), table_name='card_prints')
    op.drop_table('card_prints')
    op.drop_index(op.f('ix_card_legalities_id'), table_name='card_legalities')
    op.drop_table('card_legalities')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_decks_name'), table_name='decks')
    op.drop_index(op.f('ix_decks_id'), table_name='decks')
    op.drop_index(op.f('ix_decks_format'), table_name='decks')
    op.drop_index(op.f('ix_decks_archetype'), table_name='decks')
    op.drop_table('decks')
    op.drop_index(op.f('ix_cards_oracle_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
